HARDWARE:
  DEVICE: "cuda:0"
  NUM_WORKERS: 4
  AMP: false

MODEL:
  NAME: "yolov1"
  BACKBONE: "resnet18"
  NUM_ANCHORS: 2
  SCALE: 64
  CLASSIFIER_PATH: ""
  DETECTOR_PATH: ""
  ANCHORS_PATH: ""

TRAIN:
  DETECTOR:
    IMAGE_SIZE: 448
    BATCH_SIZE: 16
    ACC_ITER: 4
    OPTIM:
      TYPE: "adam"
      LR: 0.0001
      DECAY: 0.0005
      MOMENTUM: 0
    START_EPOCH: 0
    END_EPOCH: 30
    MULTISCALE: false
    SAVE:
      DIR: "artifacts/yolov1/resnet18"
      INTERVAL: 10
  CLASSIFIER:
    IMAGE_SIZE: 224
    BATCH_SIZE: 128
    ACC_ITER: 1
    OPTIM:
      TYPE: "adam"
      LR: 0.001
      DECAY: 0.0005
      MOMENTUM: 0
    START_EPOCH: 100
    END_EPOCH: 100
    FINETUNE:
      EPOCH: 10
      BATCH_SIZE: 64
      IMAGE_SIZE: 448
    SAVE:
      DIR: ""
      INTERVAL: 1

INFERENCE:
  METHOD: "torchvision"
  CONF_THRESH: 0.3
  NMS_THRESH: 0.5
