HARDWARE:
  DEVICE: "cuda:0"
  NUM_WORKERS: 4
  AMP: false

MODEL:
  NAME: "yolov1"
  BACKBONE: "extraction"
  NUM_ANCHORS: 3
  SCALE: 64
  CLASSIFIER_PATH: ""
  DETECTOR_PATH: ""
  ANCHORS_PATH: ""

TRAIN:
  DETECTOR:
    IMAGE_SIZE: 448
    BATCH_SIZE: 16
    ACC_ITER: 4
    OPTIM:
      TYPE: "sgd"
      LR: 0.0001
      DECAY: 0.0005
      MOMENTUM: 0.9
    START_EPOCH: 10
    END_EPOCH: 30
    MULTISCALE: false
    SAVE:
      DIR: "artifacts/yolov1/extraction"
      INTERVAL: 10
  CLASSIFIER:
    IMAGE_SIZE: 224
    BATCH_SIZE: 64
    ACC_ITER: 1
    OPTIM:
      TYPE: "adam"
      LR: 0.001
      DECAY: 0.0005
      MOMENTUM: 0.9
    START_EPOCH: 0
    END_EPOCH: 100
    FINETUNE:
      EPOCH: 10
      IMAGE_SIZE: 448
      BATCH_SIZE: 32
    SAVE:
      DIR: ""
      INTERVAL: 1

INFERENCE:
  METHOD: "torchvision"
  CONF_THRESH: 0.3
  NMS_THRESH: 0.5
  PARAMETER:
    CONFLUENCE_THRESH: 0.5
    SIGMA: 0.5
    BETA: 1.2
