HARDWARE:
  DEVICE: "cuda:0"
  NUM_WORKERS: 4
  AMP: false

MODEL:
  NAME: "yolov2"
  BACKBONE: "darknet19"
  NUM_ANCHORS: 5
  SCALE: 32
  CLASSIFIER_PATH: "artifacts/darknet19/darknet19.pth"
  DETECTOR_PATH: ""
  ANCHORS_PATH: "configs/yolov2/anchors.voc.txt"

TRAIN:
  DETECTOR:
    IMAGE_SIZE: 416
    BATCH_SIZE: 16
    ACC_ITER: 4
    OPTIM:
      TYPE: "adam"
      LR: 0.0001
      DECAY: 0.0005
      MOMENTUM: 0.9
    START_EPOCH: 10
    END_EPOCH: 30
    MULTISCALE: false
    SAVE:
      DIR: "artifacts/yolov2/darknet19"
      INTERVAL: 10
  CLASSIFIER:
    IMAGE_SIZE: 224
    BATCH_SIZE: 64
    ACC_ITER: 1
    OPTIM:
      TYPE: "adam"
      LR: 0.001
      DECAY: 0.0005
      MOMENTUM: 0.9
    START_EPOCH: 0
    END_EPOCH: 100
    FINETUNE:
      EPOCH: 10
      BATCH_SIZE: 32
      IMAGE_SIZE: 448
    SAVE:
      DIR: ""
      INTERVAL: 1

INFERENCE:
  METHOD: "torchvision"
  CONF_THRESH: 0.3
  NMS_THRESH: 0.5
